name: Checking Code Quality
on: ["push", "pull_request"]
jobs:
  eslint:
    name: Run Code Quality Static Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Dev Dependencies
        working-directory: week3/solent-room-finder-week-3
        run: npm install --only=dev
      - name: Run ESLint
        working-directory: week3/solent-room-finder-week-3
        run: npm run lint
      - name: Run TSC
        working-directory: week3/solent-room-finder-week-3
        run: npm run types
      - name: Run Prettier
        working-directory: week3/solent-room-finder-week-3
        run: npm run prettier
      - name: Run Tests
        working-directory: week9
        run: npm run test:ci
